# SPDX-FileCopyrightText: 2026 blender-cli Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""The channel contract as data: every request, every event, every shared shape.

This module is pure data and imports nothing. A plain CPython interpreter can
read it, so the build generates the CLI flag table from the same tables the
runtime validates against and `describe channel|schema` projects. There is no
second place where a field's name, type or default is written down.

Field keys: `type` (string|number|integer|boolean|array|object), `required`,
`default`, `enum`, `items` (a nested field spec), `ref` (a `DEFS` key),
`minimum`, `maximum`, `exclusive_minimum`, `doc`. Op keys: `doc`, `fields`,
`events`, `example`, `mutates` (True, False, or the set of `action` values
that change `Main`), and `exactly_one_of`.
"""

DEFS = {
    "image_policy": {
        "doc": "How pictures of a change are returned.",
        "fields": {
            "mode": {"type": "string", "enum": ["delta", "full", "off"], "default": "delta",
                     "doc": "delta crops the changed region; off sends no image event."},
            "threshold": {"type": "number", "minimum": 0, "maximum": 1, "default": 0.002,
                          "doc": "Changed-pixel fraction below which no image is sent."},
            "views": {"type": "array", "items": {"type": "string"}, "default": ["front"],
                      "doc": "Budget views rendered for feedback."},
            "pass": {"type": "string", "default": "color", "doc": "Render pass of the image."},
            "size": {"type": "integer", "minimum": 1, "default": 256,
                     "doc": "Budget tile size in pixels."},
            "samples": {"type": "integer", "minimum": 1, "default": 8,
                        "doc": "Render samples for a feedback view; fewer than an observation."},
            "overlay": {"type": "boolean", "default": True,
                        "doc": "Emit a before/after overlay of the changed region."},
            "inline": {"type": "boolean", "default": False,
                       "doc": "Return image bytes as base64 in the event instead of "
                              "writing a file."},
        },
    },
    "feedback_policy": {
        "doc": "The per-session feedback budget.",
        "fields": {
            "perception": {"type": "boolean", "default": True,
                           "doc": "Emit a perception event after every action."},
            "objective": {"type": "boolean", "default": True,
                          "doc": "Score registered targets after every action."},
            "image": {"ref": "image_policy", "doc": "Image budget."},
        },
    },
    "fit_param": {
        "doc": "One searched parameter: a program parameter or an RNA path.",
        "exactly_one_of": ["name", "path"],
        "fields": {
            "name": {"type": "string", "doc": "Program parameter name in the P block."},
            "path": {"type": "string", "doc": "RNA path assigned directly instead."},
            "min": {"type": "number", "required": True, "doc": "Lower bound."},
            "max": {"type": "number", "required": True, "doc": "Upper bound."},
        },
    },
    "fit_objective": {
        "doc": "What the search minimises or maximises.",
        "fields": {
            "target": {"type": "string", "doc": "Single target name."},
            "targets": {"type": "array", "items": {"type": "string"},
                        "doc": "Several target names, combined by weights."},
            "weights": {"type": "array", "items": {"type": "number"}, "doc": "Per-target weights."},
            "metric": {"type": "string", "enum": ["iou", "chamfer", "ssim", "hist"],
                       "default": "iou", "doc": "Metric to optimise."},
            "code": {"type": "string", "doc": "Python expression returning a score instead."},
        },
    },
    "fit_budget": {
        "doc": "The bound on a search.",
        "fields": {
            "evals": {"type": "integer", "minimum": 1, "default": 200,
                      "doc": "Maximum evaluations."},
            "seconds": {"type": "number", "minimum": 0, "exclusive_minimum": True,
                        "doc": "Wall-clock bound."},
            "size": {"type": "integer", "minimum": 1, "default": 128,
                     "doc": "Tile size used while searching."},
        },
    },
}

REQUESTS = {
    "exec": {
        "doc": "Run Python in the session namespace and push its consequences.",
        "mutates": True,
        "exactly_one_of": ["code", "script"],
        "fields": {
            "code": {"type": "string",
                     "doc": "Python source; exactly one of code or script is required."},
            "script": {"type": "string",
                       "doc": "Absolute path of a Python file to run instead of code."},
            "record": {"type": "boolean", "default": True,
                       "doc": "Record this statement as the program's next step."},
            "timeout": {"type": "number", "minimum": 0, "exclusive_minimum": True,
                        "doc": "Cooperative wall-clock deadline in seconds."},
            "feedback": {"ref": "image_policy",
                         "doc": "Image policy override for this request only."},
        },
        "events": ["log", "value", "diff", "perception", "objective", "image", "done", "error"],
        "example": {"id": 7, "op": "exec", "code": "bpy.ops.mesh.primitive_cube_add()",
                    "record": True},
    },
    "program": {
        "doc": "Read or edit the program that reproduces the scene.",
        "mutates": {"set", "patch", "run", "rollback"},
        "fields": {
            "action": {"type": "string", "required": True,
                       "enum": ["get", "set", "patch", "run", "history", "rollback", "record"],
                       "doc": "Program operation."},
            "text": {"type": "string", "doc": "Replacement program text for set."},
            "old": {"type": "string", "doc": "Text to replace for patch; must match exactly once."},
            "new": {"type": "string", "doc": "Replacement text for patch."},
            "label": {"type": "string", "doc": "Label for the version this creates."},
            "version": {"type": "string", "doc": "Version hash or label for rollback."},
            "on": {"type": "boolean", "doc": "Recording state for record."},
            "from_step": {"type": "integer", "minimum": 1,
                          "doc": "First step to re-execute for run."},
            "feedback": {"ref": "image_policy",
                         "doc": "Image policy override for this request only."},
        },
        "events": ["log", "diff", "perception", "objective", "image", "done", "error"],
        "example": {"id": 8, "op": "program", "action": "get"},
    },
    "target": {
        "doc": "Bind a reference image to a view; targets are scored after every action.",
        "mutates": False,
        "fields": {
            "action": {"type": "string", "required": True, "enum": ["set", "list", "clear"],
                       "doc": "Target operation."},
            "name": {"type": "string", "doc": "Target name."},
            "ref": {"type": "string", "doc": "Reference image path."},
            "view": {"type": "string", "default": "front",
                     "doc": "Preset view the reference is bound to."},
            "mask": {"type": "string", "enum": ["auto", "none"], "default": "auto",
                     "doc": "Reference background removal."},
            "fit": {"type": "string", "enum": ["bbox", "none"], "default": "bbox",
                    "doc": "Reference normalisation."},
            "metrics": {"type": "array", "items": {"type": "string",
                                                   "enum": ["iou", "chamfer", "ssim", "hist"]},
                        "default": ["iou"], "doc": "Metrics scored for this target."},
        },
        "events": ["log", "done", "error"],
        "example": {"id": 9, "op": "target", "action": "set", "name": "front",
                    "ref": "reference.png", "view": "front"},
    },
    "fit": {
        "doc": "Search parameters against the registered targets inside the process.",
        "mutates": True,
        "fields": {
            "params": {"type": "array", "required": True, "items": {"ref": "fit_param"},
                       "doc": "Parameters to search."},
            "objective": {"ref": "fit_objective", "doc": "What to optimise."},
            "budget": {"ref": "fit_budget", "doc": "Search bound."},
            "method": {"type": "string", "enum": ["coordinate", "nelder-mead", "random"],
                       "default": "coordinate", "doc": "Search method."},
        },
        "events": ["log", "progress", "diff", "perception", "objective", "image", "done", "error"],
        "example": {"id": 10, "op": "fit",
                    "params": [{"name": "handle_x", "min": 0.2, "max": 0.6}],
                    "objective": {"target": "front", "metric": "iou"},
                    "budget": {"evals": 40}, "method": "coordinate"},
    },
    "inspect": {
        "doc": "Read scene state from RNA.",
        "mutates": False,
        "fields": {
            "object": {"type": "string", "doc": "Restrict the objects array to this name."},
            "full": {"type": "boolean", "default": False,
                     "doc": "Expand node trees and modifier settings."},
            "select": {"type": "array", "items": {"type": "string"},
                       "doc": "RNA paths resolved relative to bpy.data."},
        },
        "events": ["log", "done", "error"],
        "example": {"id": 11, "op": "inspect", "object": "Cube", "full": False},
    },
    "observe": {
        "doc": "Render deterministic offscreen views.",
        "mutates": False,
        "fields": {
            "views": {"type": "array", "items": {"type": "string"}, "default": ["front", "persp"],
                      "doc": "Preset views."},
            "passes": {"type": "array", "items": {"type": "string"}, "default": ["color"],
                       "doc": "Render passes."},
            "size": {"type": "integer", "enum": [512, 768, 1024], "default": 512,
                     "doc": "Tile size."},
            "ref": {"type": "string", "doc": "Reference image placed beside the first view."},
            "layout": {"type": "string", "enum": ["sheet", "separate"], "default": "sheet",
                       "doc": "One contact sheet or one file per view and pass."},
            "overlay": {"type": "boolean", "default": False,
                        "doc": "Blend the reference over the first tile."},
            "frame": {"type": "string", "doc": "Object whose bounds frame the views."},
            "out": {"type": "string", "doc": "Output file, or directory for separate layout."},
            "inline": {"type": "boolean", "default": False,
                       "doc": "Return base64 instead of writing files."},
        },
        "events": ["log", "done", "error"],
        "example": {"id": 12, "op": "observe", "views": ["front"], "passes": ["color"],
                    "size": 512},
    },
    "describe": {
        "doc": "Answer from live RNA, the agent helpers or the channel registry.",
        "mutates": False,
        "fields": {
            "path": {"type": "string", "required": True,
                     "doc": "RNA path, agent path, `channel` or `schema`."},
        },
        "events": ["log", "done", "error"],
        "example": {"id": 13, "op": "describe", "path": "bpy.ops.mesh.bevel"},
    },
    "session": {
        "doc": "Session state: snapshots, history, feedback policy and lifetime.",
        "mutates": {"rollback"},
        "fields": {
            "action": {"type": "string", "required": True,
                       "enum": ["status", "feedback", "save", "close", "snapshot", "rollback",
                                "history"],
                       "doc": "Session operation."},
            "label": {"type": "string",
                      "doc": "Snapshot label; a labelled snapshot is also written to disk."},
            "snapshot": {"type": "string", "doc": "Snapshot hash, label or ~N for rollback."},
            "file": {"type": "string", "doc": "Path for save."},
            "feedback": {"ref": "feedback_policy", "doc": "Feedback policy to merge."},
        },
        "events": ["log", "diff", "perception", "objective", "image", "done", "error"],
        "example": {"id": 14, "op": "session", "action": "status"},
    },
    "cancel": {
        "doc": "Stop the running request. Answered on the transport thread, out of order.",
        "mutates": False,
        "fields": {
            "target": {"type": "integer", "required": True,
                       "doc": "id of the request to stop."},
        },
        "events": ["done"],
        "example": {"id": 15, "op": "cancel", "target": 10},
    },
}

EVENTS = {
    "log": {"doc": "Captured Python stdout or stderr, emitted line by line as it is produced.",
            "fields": {"stream": {"type": "string", "enum": ["stdout", "stderr"]},
                       "text": {"type": "string"}}},
    "value": {"doc": "repr of the statement's final expression, or null when there is none.",
              "fields": {"value": {"type": "string"}}},
    "diff": {"doc": "Datablocks the request added, changed or removed, and the new state.",
             "fields": {"added": {"type": "array"}, "changed": {"type": "array"},
                        "removed": {"type": "array"}, "snapshot": {"type": "string"},
                        "step": {"type": "integer"}}},
    "perception": {"doc": "Counts, bounds, framing and what changed in the budget view.",
                   "fields": {"objects": {"type": "integer"}, "verts": {"type": "integer"},
                              "faces": {"type": "integer"}, "bounds": {"type": "object"},
                              "dims": {"type": "array"}, "framing": {"type": "object"},
                              "changed": {"type": "object"}, "symmetry": {"type": "object"}}},
    "objective": {"doc": "Per-target metrics, their deltas and the best state so far.",
                  "fields": {"targets": {"type": "object"}, "best": {"type": "object"}}},
    "image": {"doc": "A picture of the change, or a requested frame.",
              "fields": {"kind": {"type": "string", "enum": ["delta", "full", "overlay", "error"]},
                         "view": {"type": "string"}, "pass": {"type": "string"},
                         "path": {"type": "string"}, "inline": {"type": "string"},
                         "size": {"type": "array"}, "region": {"type": "array"}}},
    "progress": {"doc": "Search progress, at most every 0.5 s.",
                 "fields": {"eval": {"type": "integer"}, "of": {"type": "integer"},
                            "best": {"type": "number"}, "params": {"type": "object"}}},
    "done": {"doc": "Terminal success event, carrying the op-specific result fields.",
             "fields": {"ok": {"type": "boolean"}, "ms": {"type": "number"}}},
    "error": {"doc": "Terminal failure event.",
              "fields": {"ok": {"type": "boolean"}, "type": {"type": "string"},
                         "message": {"type": "string"}, "line": {"type": "integer"},
                         "rna": {"type": "object"}, "fix": {"type": "object"},
                         "autosave": {"type": "string"}}},
}
